server:
  port: 8080
  servlet:
    context-path: /api
    # cookie过期时间
    session:
      cookie:
        max-age: 2592000

# 日志具体配置 - Logback生效
logging:
  # 控制台日志输出格式【核心：必须带%clr() 才会有颜色】
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
  # 可选：配置日志级别（比如让debug日志也显示）
  level:
    root: INFO
    com:
      yourpackage: DEBUG # 你的业务包路径
spring:
  # SpringBoot 日志核心配置 - 开启彩色日志
  output:
    ansi:
      enabled: ALWAYS
      # ansi颜色编码支持，默认就是ALWAYS，无需额外配置
      console-available: true
  application:
    name: yu-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_picture
    username: root
    password: sphz0361
  profiles:
    active: local
  # 文件上传体积配置
  servlet:
    multipart:
      max-file-size: 10MB
  # redis 配置
  redis:
    database: 0
    host: 192.168.88.130
    password: sphz0361
    port: 6379
    timeout: 5000
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted #全局的 Entity 逻辑删除字段属性名，仅在逻辑删除功能打开时有效。
      logic-delete-value: 1 #逻辑已删除值(默认值：1)
      logic-not-delete-value: 0 #逻辑未删除值(默认值：0)
# 接口文档
knife4j:
  enable: true
  openapi:
    title: doc
    version: 1.0
    group:
      test1:
        api-rule: package
        api-rule-resources:
          - com.yupi.yupicturebackend.controller



#knife4j:
#  enable: true
#  openapi:
#    title: Knife4j官方文档
#    description: "`我是测试`,**你知道吗**
#    # aaa"
#    email: xiaoymin@foxmail.com
#    concat: 八一菜刀
#    url: https://docs.xiaominfo.com
#    version: v4.0
#    license: Apache 2.0
#    license-url: https://stackoverflow.com/
#    terms-of-service-url: https://stackoverflow.com/
#    group:
#      test1:
#        group-name: 分组名称
#        api-rule: package
#        api-rule-resources:
#          - com.yupi.yupicturebackend.controller